from rest_framework import serializers
from django.contrib.auth import get_user_model, authenticate
from .models import Product

User = get_user_model()

# --- User Serializers ---

class UserRegistrationSerializer(serializers.ModelSerializer):
    # Ensure password confirmation is handled here
    password2 = serializers.CharField(style={'input_type': 'password'}, write_only=True)
    
    class Meta:
        model = User
        fields = ('id', 'email', 'username', 'password', 'password2', 'phone_number', 'avatar')
        extra_kwargs = {'password': {'write_only': True}}
        read_only_fields = ('id',) # 'id' is generated by the database

    def validate(self, data):
        if data['password'] != data['password2']:
            raise serializers.ValidationError({"password": "Passwords must match."})
        data.pop('password2')
        return data

    def create(self, validated_data):
        user = User.objects.create_user(**validated_data)
        return user

class UserProfileSerializer(serializers.ModelSerializer):
    # CRITICAL FIX: Explicitly define 'id' as a ReadOnlyField 
    # to handle the MongoDB ObjectId serialization properly.
    id = serializers.ReadOnlyField(source='_id')
    
    class Meta:
        model = User
        fields = ('id', 'email', 'username', 'phone_number', 'balance', 'avatar')

class ChangePasswordSerializer(serializers.Serializer):
    old_password = serializers.CharField(required=True)
    new_password = serializers.CharField(required=True)
    # You might want to add new_password_confirm for validation, but keeping simple for now.

# --- Product Serializer ---
# class ProductSerializer(serializers.ModelSerializer):
#     seller_id = serializers.ReadOnlyField(source="seller_id")
#     buyer_id = serializers.ReadOnlyField(source="buyer_id")
#     seller_name = serializers.ReadOnlyField(source='seller.email')
#     id = serializers.ReadOnlyField(source='_id')
#     # def to_representation(self, instance):
#     # def to_representation(self, instance):
#     #     representation = super().to_representation(instance)
        
#     #     # Accessing instance.pk (which holds the ObjectId) and converting it to a string for debugging
#     #     product_pk_str = str(instance.pk) 
        
#     #     # The 'id' in representation is what will be in the JSON.
#     #     print(f"✅ FINAL JSON OUTPUT ID (Now checking representation.get('id')): {representation.get('id')} for product: {instance.title}")
        
#     #     # Check if the field is None, and manually set it if necessary (for robust debugging)
#     #     if representation.get('id') is None:
#     #          representation['id'] = product_pk_str
#     #          print(f"⚠️ FORCED ID: Manually set 'id' to: {product_pk_str}")
        
#     #     return representation
#     def to_representation(self, instance):
#         representation = super().to_representation(instance)

#     # Convert ObjectId → string
#         product_pk_str = str(instance.pk)

#     # Ensure ID exists
#         if representation.get('id') is None:
#            representation['id'] = product_pk_str

#     # ---- GET MONGODB RAW FIELDS ----
#     # instance.__dict__ contains all real MongoDB fields
#         mongo_data = instance.__dict__

#         seller_id = mongo_data.get("seller_id")
#         buyer_id = mongo_data.get("buyer_id")

#     # Add them to the JSON response
#         representation['seller_id'] = str(seller_id) if seller_id else None
#         representation['buyer_id'] = str(buyer_id) if buyer_id else None

#         return representation
#     class Meta:
#         model = Product
#         # FIX 1: List all fields explicitly instead of using ('id', '__all__')
#         fields = (
#             'id', 
#             'seller_name', 
#             'name',
#             'title',
#             'description',
#             'status',
#             'price',
#             'location',
#             'category',
#             'image',
#             # You can also add created_at, but keep it minimal
#               # add these fields
#             'seller_id',
#             'buyer_id',
#         )
#         # Note: You don't need to list seller/buyer here as they are read-only Foreign Keys
#         # that DRF knows how to manage based on the model.
#         read_only_fields = ('seller', 'buyer', 'status', 'created_at')

class ProductSerializer(serializers.ModelSerializer):
    seller_id = serializers.ReadOnlyField(source="seller_id")

    buyer_id = serializers.ReadOnlyField(source="buyer_id")
    seller_name = serializers.ReadOnlyField(source='seller.email')
    id = serializers.ReadOnlyField(source='_id')
    class Meta:
        model = Product
        fields = (
            'id',
            'seller_name',
            'name',
            'title',
            'description',
            'status',
            'price',
            'location',
            'category',
            'image',
            'seller_id',
            'buyer_id',
        )
        read_only_fields = ('seller', 'buyer', 'status', 'created_at')

    def to_representation(self, instance):
        representation = super().to_representation(instance)

    # ID
        representation['id'] = str(getattr(instance, 'pk', None))

    # Seller & Buyer IDs
        seller_id = getattr(instance, 'seller_id', None)
        buyer_id = getattr(instance, 'buyer_id', None)

        representation['seller_id'] = str(seller_id) if seller_id else None
        representation['buyer_id'] = str(buyer_id) if buyer_id else None

        return representation